# [module.hugoVersion]
# min = "0.111.3"

[[module.imports]]
path = "github.com/hbstack/hb"

[[module.imports]]
path = "github.com/hbstack/form"

[[module.imports]]
path = "github.com/hbstack/snackbar"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/bootstrap"

[[module.imports]]
path = "github.com/hugomods/recaptcha-v2"
